# Generated by Django 3.1.2 on 2020-10-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapyitem',
            name='data',
        ),
        migrations.AddField(
            model_name='scrapyitem',
            name='deliveryDate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scrapyitem',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='scrapyitem',
            name='pictures',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='scrapyitem',
            name='price',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scrapyitem',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
